import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="sticky top-0 z-50 border-b bg-white/80 backdrop-blur">
          <div className="max-w-5xl mx-auto px-4 py-3 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src="/logo.png" alt="TitiFarm" className="h-12 md:h-14 w-auto" />
            </Link>
            <nav className="space-x-4 text-sm">
              <Link href="/" className="hover:underline">Trang chủ</Link>
              <Link href="/login" className="hover:underline">Đăng nhập</Link>
              <Link href="/orders" className="hover:underline">Đơn của tôi</Link>
            </nav>
          </div>
        </header>
        <main className="max-w-5xl mx-auto px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
